// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZAOEWqKQCtgBbWR-vkOpTHTKqD4lLpqo',
    appId: '1:104722668131:web:520cf4b97fecb8d6c7b656',
    messagingSenderId: '104722668131',
    projectId: 'app-chat-fa55f',
    authDomain: 'app-chat-fa55f.firebaseapp.com',
    storageBucket: 'app-chat-fa55f.appspot.com',
    measurementId: 'G-5ZN08J4RR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlLEpYkpBpFxDTfeK6R0ZqmcnUEjdVugk',
    appId: '1:104722668131:android:eaf71d0abcf757dac7b656',
    messagingSenderId: '104722668131',
    projectId: 'app-chat-fa55f',
    storageBucket: 'app-chat-fa55f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0ZgDLq3IYYD00LlSb6H9Mt2LDszqTeUY',
    appId: '1:104722668131:ios:e0f2f5396133bc8ec7b656',
    messagingSenderId: '104722668131',
    projectId: 'app-chat-fa55f',
    storageBucket: 'app-chat-fa55f.appspot.com',
    iosBundleId: 'com.example.appChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0ZgDLq3IYYD00LlSb6H9Mt2LDszqTeUY',
    appId: '1:104722668131:ios:e0f2f5396133bc8ec7b656',
    messagingSenderId: '104722668131',
    projectId: 'app-chat-fa55f',
    storageBucket: 'app-chat-fa55f.appspot.com',
    iosBundleId: 'com.example.appChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZAOEWqKQCtgBbWR-vkOpTHTKqD4lLpqo',
    appId: '1:104722668131:web:3cdca72d4915753ac7b656',
    messagingSenderId: '104722668131',
    projectId: 'app-chat-fa55f',
    authDomain: 'app-chat-fa55f.firebaseapp.com',
    storageBucket: 'app-chat-fa55f.appspot.com',
    measurementId: 'G-YVBHL4YJLH',
  );
}
